
<link href="<?php echo $path_to_root ?>/modules/kanban/css/kanban.css" rel="stylesheet" type="text/css" />
	
<div id="kanban_wrapper">
	<div id="kanban_board"></div>
	<div class="clear"></div>

	<div id="member_filter" class="member_filter">
		<div id="filter_header">Project members</div>
	</div>
</div>

<script type="text/javascript" src="../js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="../js/jquery.dragsort-0.5.2.js" ></script>
<script type="text/javascript" src="../js/config.js" ></script>
<script type="text/javascript" src="../js/kanban.js" ></script>
